### ISSUE TITLE
Dropzone disable attribute not working

### ISSUE THREAD

**Issue by stefanstankovic995** [Yuvaleros/material-ui-dropzone#103]
Latest version of dropzone does not get disabled after setting prop disable to true.

**Comment by georgiydubrov** [comment]
@stefanstankovic995 Current library doesn't have such prop. Try ask here - [react-dropzone](https://github.com/react-dropzone/react-dropzone).

**Comment by thminggg** [comment]
Hi @georgiydubrov , the react-dropzone has provided `disabled, noClick, noDrag` in [react-dropzone](https://react-dropzone.js.org).

I tried to pass the `disabled, noClick, noDrag` props in material-ui-dropzone which are not passed  to the downstream component

Here is how the Component tree shown in Chrome dev tool
```
<DropzoneArea disabled noClick noDrag>
      <Dropzone {// above props not shown up here}/>
<DropzoneArea>
```

Could this be resolved like passing `{...props}` to `<Dropzone />`?
