### ISSUE TITLE
Allow Dropzone to accept jp2 (jpeg2000) files

### ISSUE THREAD

**Issue by Tassfighter** [Yuvaleros/material-ui-dropzone#106]
My image.jp2 works with drag&drop.

But the case open with explorer does not work. The image.jp2 is not shown in the explorer.
acceptedFiles={['image/*']}
acceptedFiles={['image/*', 'image/jp2']}

I can leave acceptedFiles={[]} empty. But then all files are shown, I only want to allow images.

**Comment by panz3r** [comment]
Hi @Tassfighter ,

Which version of `material-ui-dropzone` are you using?

**Comment by panz3r** [comment]
Upon further investigation, this issue seems more related to `react-dropzone` module (used internally by `material-ui-dropzone`) so please refer to their doc about accepting specific file types [here](https://react-dropzone.js.org/#section-accepting-specific-file-types).

Closing this issue.
