### ISSUE TITLE
Fully support setting `acceptedFiles` as `.fileending`

### ISSUE THREAD

**Issue by wirmar** [Yuvaleros/material-ui-dropzone#107]
`input type=file` also supports setting the `acceptedFiles` as file endings. (e.g `[".jpg", ".png"]`), see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#Unique_file_type_specifiers
This is useful for custom file types whose mime type is not known by the browser.

What already works:
* When clicking the dropzone to open the file explorer to select a file, the files are already filtered to only show the files with the provided file endings. (Tested on windows)
* When dropping an unsupported or supported file ending the file is accepted or rejected as expected.

What doesn't work:
* When hovering a file over the dropzone it always shows the "wrong file type" hover state (red), even if the file is accepted when dropped.

**Comment by panz3r** [comment]
Should be resolved as of PR #121 .

For more details about supported file types and filters see section `Accepting specific file types
` of `react-dropzone` docs [here](https://react-dropzone.js.org/#section-accepting-specific-file-types).

**Comment by Camsteack** [comment]
Hi,
This doesn't seem to be work on the last version 3.2.1. When I hover the dropzone I still always shows the rejected red state if I use file extensions, but reading the react-dropzone documentation it won't be working anyway no ?

Thanks a lot

**Comment by sli** [comment]
I'm having an issue similar the @camsteack. I added `.csv` to `acceptedFiles` to get around Windows not setting the text/csv MIME type when uploading the file. The dropzone _does_ accept CSV files but the dropzone turns red as though it will reject them.

**Comment by sli** [comment]
Yep, I can confirm that the described bug is present (still or again) in 3.3.0.
