### ISSUE TITLE
SnackbarAlert not visible on iOS

### ISSUE THREAD

**Issue by jnystrom** [Yuvaleros/material-ui-dropzone#123]
I am using the dialog component, and when trying to use this on IOS, it is not working.  I am able to click the component, and get the choice to get file from camera roll, but then I select one, and continue, and the component does not do anything.  I am not able to get the submit button to show, am I missing something?  Thanks.

**Comment by panz3r** [comment]
Hi @jnystrom ,

I made some testing and couldn't reproduce your issue.

Can you please try the one hosted here https://panz3r.github.io/material-ui-dropzone/#!/DropzoneDialog and see if it works for you?

**Comment by jnystrom** [comment]
Ok, I did test, and the image files seemed to work, even when I tried it in my app.  I guess the issue is on mobile when the file, in my case a video file, is to big or file type is wrong, the toast notification of the error is not visible.

**Comment by panz3r** [comment]
This issue should be resolved thanks to the addition of the `showAlerts` and `onAlert` props.

If the `Snackbar` is not working, you can try to disable the built-in one (by setting `showAlerts` to `false`) and implement you r own notifications logic (using the `onAlert` prop).
