### ISSUE TITLE
Allow Dropzone to accept xml files.

### ISSUE THREAD

**Issue by schatterjee-erwin** [Yuvaleros/material-ui-dropzone#13]
I am trying to add xml files but it is unable to support it.Would be great if this feature is added.

Thanks

**Comment by Yuvaleros** [comment]
You can add to the "acceptedFiles" prop any type you wish, including xml.

**Comment by JoeIngledew** [comment]
@schatterjee-erwin you're looking for the 'application/xml' MIME type, I believe

**Comment by schatterjee-erwin** [comment]
@JoeIngledew I have tried adding 'applciation/xml' but it gives me an error that says "xyz.xml is rejected. File type not supported".

**Comment by schatterjee-erwin** [comment]
@JoeIngledew @Yuvaleros  I found the issue on my side. It is due to the maxFileSize that it keeps rejecting the files that are above '3000000'. Otherwise it works!. Thanks

**Comment by Yuvaleros** [comment]
Great, closing the issue.
