### ISSUE TITLE
Better behaviour for Preview when used for single images

### ISSUE THREAD

**Issue by max-carroll** [Yuvaleros/material-ui-dropzone#130]
When you want to have an upload for a single image I think it should behave a bit differently

For instance, the image should expand to fill the entirety of the drop zone rather than appear as a small square. 

Small squares definitely makes sense if you have multiple images to add, however in the scenario of uploading a single image then the image looks a little lonely and the component seems a little incomplete.

Would like to suggest that we extend to perhaps have a singleImagePreview: boolean prop or something that we can set that gets it to behave in such a way.

I need to this for my site, I'm wondering whether you guys would like this feature too then perhaps I can work on this source code, otherwise if no one is on board I can always fork it and do it for myself

![image](https://user-images.githubusercontent.com/13512675/79367043-15986000-7f45-11ea-8fba-bc527a777520.png)

just thinking if we did implement this then it may make sense to have a single prop for how we want to display the preview so we could have a prop like

previewType : string - and it could be either ['insideDropzone','outSideDropzone,'singleImagePreview']

I havent tested this I was just trying to think how logically this might be achieved, will be interested to hear your thoughts on this 

![image](https://user-images.githubusercontent.com/13512675/79368132-d2d78780-7f46-11ea-9843-685a875eb2c9.png)

or on the other hand maybe we dont need to pass in any particular props at all because this is probably always desired when the filesLimit is one 

![image](https://user-images.githubusercontent.com/13512675/79370981-82165d80-7f4b-11ea-9bd8-44ec14e2425b.png)

**Comment by panz3r** [comment]
Hi @max-carroll ,

Thanks for your feedback and sorry for the late answer.

> just thinking if we did implement this then it may make sense to have a single prop for how we want to display the preview so we could have a prop like
previewType : string - and it could be either ['insideDropzone','outSideDropzone,'singleImagePreview']

I like this idea and I was thinking about something like that for `v3.0` and also to deprecate the current props using the `warning` lib (which would require a bit of setup).

Regarding the main issue If I'd have to choose I'd go for this one 
> on the other hand maybe we dont need to pass in any particular props at all because this is probably always desired when the filesLimit is one

Let me know if you thing you can try to put together a PR with this changes or need more help.

Also I'd like to review a bit the style of the preview to better match Material Design specs so any suggestion about how to re-design this is greatly appreciated.

**Comment by max-carroll** [comment]
Thank you @panz3r , I will do some code changes and see what you guys think. Should I checkout a new branch v3.x from v2.x then and we can just keep merging the changes in? or shall I just work in a branch off v2.x now?

**Comment by panz3r** [comment]
Hi @max-carroll ,

> Should I checkout a new branch v3.x from v2.x then and we can just keep merging the changes in? or shall I just work in a branch off v2.x now?

You can start a new branch from `master` (which is `v3.x` at the moment), back-porting to branch `v2.x` should be easy enough after the changes will be merged 😉 .

> Awesome Ill see If I can checkout the Material Design spec and read some articles about drop zones

You can start by looking at the official Material Design specs [here](https://www.material.io) and see the already available components from Material-UI [here](https://material-ui.com).

Thanks again for your feedback and support, looking forward to your PR.

**Comment by shasu01** [comment]
Can you assist me? my File Limit is 1 but the image alignment is offbeat and the delete icon is far from the image 
const baseStyle = {
      padding: '20px',
      borderWidth: 2,
      borderRadius: 2,
      borderColor: '#eeeeee',
      borderStyle: 'dashed',
      backgroundColor: '#fafafa',
      color: '#bdbdbd',
      outline: 'none',
      transition: 'border .24s ease-in-out'
    };
    

       <DropzoneArea  className={classes.baseStyle} acceptedFiles={['image/*', 'application/pdf']} filesLimit={1} maxFileSize={100000} dropzoneText='Drag and drop an image file here or click'
            onChange={this.handleChange.bind(this)}  showPreviewsInDropzone={true} fullWidth={false} previewGridProps={{  container: { spacing: 0}   }}   showAlerts={true}   />

![image](https://user-images.githubusercontent.com/30653592/81257976-eb622b80-9034-11ea-8dc5-05c3ee68f1ce.png)

**Comment by max-carroll** [comment]
This is tee actual code for the PreviewList

![image](https://user-images.githubusercontent.com/13512675/81267639-b22eb900-903e-11ea-8eb2-e8ea8b93fdd5.png)

At the moment the default size of the item is xs={4} which is 4/12s of the grid, you could pass a prop in here of xs: 1 or whatever you like to change this  behaviour.

Check the previewGridProps.item

**Comment by shasu01** [comment]
Thank you.
It worked

item: { xs: 12},

**Comment by shasu01** [comment]
Where do I find the code to find solutions myself. Im now having issue with
delete icon too far away
[image: image.png]

**Comment by max-carroll** [comment]
look at the top of this page, there's a code tab 😊

**Comment by panz3r** [comment]
Since the "Preview" section is getting a lot of attention in the last period, we're going to improve it a bit.
You can follow the development and contribute with your ideas/feedbacks on this issue #166 .

Closing this issue in favour of the new "umbrella" one.
