### ISSUE TITLE
Development environment setup

### ISSUE THREAD

**Issue by panz3r** [Yuvaleros/material-ui-dropzone#131]
Hi I know this isnt the best forum for this, but Im trying to help out on this project Im wondering what the best setup is for dev, I ran npm install and npm start in both the root directory and the example directory then I edit both the example and root source to see if it works. But sometimes I get funny errors and Im wondering if this is the best workflow setup. If someone just helps me get organized Ill do a bit of work on this 😀

_Originally posted by @max-carroll in https://github.com/Yuvaleros/material-ui-dropzone/pull/110#issuecomment-614202903_

**Comment by panz3r** [comment]
Hi @max-carroll,

Sorry for the delay of this answer.

Recently the `master` branch has switched to [`yarn v1.x`](https://classic.yarnpkg.com/lang/en/) as the default package manager instead of `npm`, so you'll need to have that installed (beside Node of course).

My current setup is as follow

```shell
> node -v 
v12.16.1

> yarn -v
1.22.4
```

Also the `example` app as been removed and replaced by examples built using [`react-styleguidist`](https://react-styleguidist.js.org) (defined inside the `.md` files next to the components code)

You can start the examples in `dev-mode` by running the following command

```shell
yarn docs:dev
```

from this point onward every change made to components or examples code is available for testing in the browser.

Let me know if this helps you or if you have further issues/questions.

**Comment by max-carroll** [comment]
@panz3r I think this is now adequately described in the CONTRIBUTING.md, should we close this?

**Comment by panz3r** [comment]
@max-carroll yes, you are right on this.

Closing this issue, see [CONTRIBUTING](https://github.com/Yuvaleros/material-ui-dropzone/blob/master/CONTRIBUTING.md) for more details.
