### ISSUE TITLE
Clear file list when submitting not working

### ISSUE THREAD

**Issue by PabloCanalSuarez** [Yuvaleros/material-ui-dropzone#141]
Hi, I'm developing an application in React where I want to **upload `.gpx` and `.json` files**, and I have a couple of questions. I'm trying to do it with the **DropzoneDialog** component, as I'd like to differentiate the uploading area a little bit from the rest. 

These are my following questions:

1. How can the **list of files** of the DropzoneDialog **be cleared when submitting**? In my case, when I click on the save button the data is processed, but I can open again the dialog and it seems the files are still "there", as I can click on save again without having to select explicitly any file. I don't know if that is a bug or I'm doing something wrong.

2. Is there any way to **disable the effect when dragging a file** onto the dropzone? I have this doubt because, in my case, as I only accept `.gpx`, `.json` or `.jsonld`, they're always recognized by the dropzone as incorrect, even if I can accept them properly later. It's just a mere ui detail that I'd like to know if it can be solved in any way.

In case it's needed, this is my code: 
```jsx
handleSave(files) {
    this.setState({
        open: false,
    });
    console.log(files)
}

render() {

    const { classes } = this.props;

    return (
        <div>
            <Button color="primary" variant='contained' className={classes.btn} onClick={() => this.handleOpen()}>
                Import Route
            </Button>
            <DropzoneDialog
                open={this.state.open}
                acceptedFiles={['.gpx', '.json', '.jsonld']}
                showPreviews={true}
                showPreviewsInDropzone={false}
                maxFileSize={5000000}
                onSave={(files) => this.handleSave(files)}
                onClose={this.handleClose.bind(this)}
                submitButtonText={"import"}
                cancelButtonText={"cancel"}
                dialogTitle={"Import routes"}
                dropzoneText={"Drag and drop any GPX or JSON route files"}
            />
        </div>
    );
}
```

**Comment by panz3r** [comment]
Hi @PabloCanalSuarez ,

Thanks for your feedback, I'll try to answer your questions.

> 1. How can the list of files of the DropzoneDialog be cleared when submitting? In my case, when I click on the save button the data is processed, but I can open again the dialog and it seems the files are still "there", as I can click on save again without having to select explicitly any file. I don't know if that is a bug or I'm doing something wrong.

To trigger the cleanup of uploaded file you should use the `clearOnUnmount` prop and set that to `true`.

> 2. Is there any way to disable the effect when dragging a file onto the dropzone? I have this doubt because, in my case, as I only accept .gpx, .json or .jsonld, they're always recognized by the dropzone as incorrect, even if I can accept them properly later. It's just a mere ui detail that I'd like to know if it can be solved in any way.

At the moment there's no option to disable this, it's a strange behaviour and I'd like to investigate it a little more but seems to be an issue dependent on `react-dropzone`, as you can see [here](https://react-dropzone.js.org/#section-accepting-specific-file-types) and at this issue [here](https://github.com/react-dropzone/react-dropzone/issues/276).

If required I'll add a new prop to disable the "validation effect" of `DropzoneArea` component.

Thanks again and let me know it this helps you.

**Comment by PabloCanalSuarez** [comment]
> To trigger the cleanup of uploaded file you should use the clearOnUnmount prop and set that to true.
Perfect!! It is working now.

> At the moment there's no option to disable this, it's a strange behaviour and I'd like to investigate it a little more but seems to be an issue dependent on react-dropzone, as you can see here and at this issue here.

Yes, I seems like an issue with react-dropzone. It could be good to add that new prop that you mentioned to disable this ui behaviour, but the rest works perfectly.

Thank you very much for your help!!

**Comment by panz3r** [comment]
Hi @PabloCanalSuarez ,

I added a new `disableRejectionFeedback` to disable the 'red-striped` feedback effect.

The changes have been merged but they are yet to be published to `npm`, for now if you need to upgrade you can install the module directly from `GitHub`

for release `v3.x`
```shell
❯ npm i yuvaleros/material-ui-dropzone#d9f1c22
```
(the same also works with `yarn`)

for release `v2.x`
```shell
❯ npm i yuvaleros/material-ui-dropzone#5af4d4e
```

To see the differences between the 2 version see the [CHANGELOG](https://github.com/Yuvaleros/material-ui-dropzone/blob/master/CHANGELOG.md).

Thanks for your feedback and patience.

**Comment by PabloCanalSuarez** [comment]
Ok, perfect!! It works now.

Thank you very much for your help.

**Comment by max-carroll** [comment]
Thanks this also solves a problem for me when using docx files, I see red-stripes when dragging a docx, when I release the file however it is not rejected. I have set up my onRejectFiles method to log them and it never fires which is weired. Will investigate this further at some point

**Comment by Parya-Jafari** [comment]
> Hi @PabloCanalSuarez ,
> 
> I added a new `disableRejectionFeedback` to disable the 'red-striped` feedback effect.
> 
> The changes have been merged but they are yet to be published to `npm`, for now if you need to upgrade you can install the module directly from `GitHub`
> 
> for release `v3.x`
> 
> ```shell
> ❯ npm i yuvaleros/material-ui-dropzone#d9f1c22
> ```
> 
> (the same also works with `yarn`)
> 
> for release `v2.x`
> 
> ```shell
> ❯ npm i yuvaleros/material-ui-dropzone#5af4d4e
> ```
> 
> To see the differences between the 2 version see the [CHANGELOG](https://github.com/Yuvaleros/material-ui-dropzone/blob/master/CHANGELOG.md).
> 
> Thanks for your feedback and patience.

Hi @panz3r! 
Thanks for adding the disableRejectionFeedback! I believe the disableRejectionFeedback prop is not included in the DropzoneAreaBaseProps type, which causes an error when using Typescript. Can you please add the disableRejectionFeedback prop to the DropzoneAreaBaseProps type?
