### ISSUE TITLE
Override :focus border styling

### ISSUE THREAD

**Issue by mattcorner** [Yuvaleros/material-ui-dropzone#146]
Would like to override the black :focus border colour but can't seem to work out how. Including in dropzoneClass styling doesn't work.

_Originally posted by @mattcorner in https://github.com/Yuvaleros/material-ui-dropzone/issues/145#issuecomment-619657990_

**Comment by panz3r** [comment]
Relatable to issue #125 , the updated theme support should also solve this one.

@mattcorner , thanks for your feedback, I don't have a clear timeframe for the above issue but we'll look into it as soon as possible.
