### ISSUE TITLE
onChange fired on mount and unmount

### ISSUE THREAD

**Issue by mattcorner** [Yuvaleros/material-ui-dropzone#153]
### Describe the bug
As of 3.0.0, the onChange method is fired on dropzone component mount, and also unmount with empty files array. This is undesirable.

### Steps to reproduce
[Code sandbox demo](https://codesandbox.io/s/wandering-forest-tz0nt?file=/src/App.js)
Note alert on page load. Note alert on toggling dropzone off so that it is unmounted.

### Expected behavior
No callback trigger on mount and unmount. I should only expect an onChange with empty files when a user has removed a file from dropzone.

### Versions

- OS: windows
- Browser: chrome, edge
- `@material-ui/core` version: latest
- `material-ui-dropzone` version: 3.0.0

**Comment by mattcorner** [comment]
It looks like the code has been specifically written to do this. I can't understand the use case. 

On mount, if I have given the component a file array, or not, I know the state so do not expect to have the callback triggered.

On unmount, I have carried out the action to unmount it, so do not expect the callback to trigger with empty. If I need to do any actions here, I'll do them when I unmount the component myself.

**Comment by mattcorner** [comment]
Just found the clearOnUnmount option which give me the unmount behaviour I expect. Wonder why I never got unmount callback triggers in 2.x.x. I guess the bug is there rather than 3.0.0

**Comment by BGehrels** [comment]
Sadly, this one got closed.

I would definitly love some documentation about this behaviour in the breaking changes section of the release notes.

**Comment by panz3r** [comment]
Hi @mattcorner and @BGehrels ,

Thanks for your feedbacks.

I updated the CHANGELOG to better explain the change about `onChange` behaviour, also to clarify the main reason behind this change is because of a better handling of the `initialFiles` prop on mount, the event is also triggered on unmount when the `clearOnUnmount` prop is set to `true`.
