### ISSUE TITLE
When is the new release of the material-ui-dropzone?

### ISSUE THREAD

**Issue by schatterjee-erwin** [Yuvaleros/material-ui-dropzone#16]
@Yuvaleros @skoging Hey guys. I would like to know when is the new release going to happen with the current changes. 

Thanks.

**Comment by Yuvaleros** [comment]
Hi @schatterjee-erwin, released the newest version to NPM

**Comment by schatterjee-erwin** [comment]
Great! Thanks @Yuvaleros
