### ISSUE TITLE
Add an option to use item-component

### ISSUE THREAD

**Issue by valik1228** [Yuvaleros/material-ui-dropzone#160]
### Describe the problem related to this feature request
Make a list of items, show their details and interact with the items inside the dropzone-area (preview images, play a video, listen to the uploaded song) regardless the upload process

### Describe the solution you'd like
Use user made component, to place the data into

Thanks for making great tool like that

**Comment by panz3r** [comment]
Since the "Preview" section is getting a lot of attention in the last period, we're going to improve it a bit.
You can follow the development and contribute with your ideas/feedbacks on this issue #166 .

Closing this issue in favour of the new "umbrella" one.
