### ISSUE TITLE
How to change the box height?

### ISSUE THREAD

**Issue by jeancarlos-cpu** [Yuvaleros/material-ui-dropzone#162]

**Comment by panz3r** [comment]
Hi @jeancarlos-cpu ,

Thanks for your feedback, this should now be possible thanks to the newly updated MUI Theme support.

Once updated, you can set the `minHeight` CSS prop of the `.MuiDropzoneArea-root` class following the `MaterialUI` customisation guide (see [here](https://material-ui.com/customization/components/) for more details).

----

The changes are yet to be published to npm (they'll get released as version `3.1.0`), for now if you need to upgrade you can install the module directly from `GitHub`

for release `v3.x`
```shell
❯ npm i yuvaleros/material-ui-dropzone#84c7225
```
(the same also works with `yarn`)

for release `v2.x`
```shell
❯ npm i yuvaleros/material-ui-dropzone#7f3ac98
```

To see the differences between the 2 version see the [CHANGELOG](https://github.com/Yuvaleros/material-ui-dropzone/blob/master/CHANGELOG.md).

----

Let me know if you have further doubts.
