### ISSUE TITLE
Update documentation Theming

### ISSUE THREAD

**Issue by wvanooijen92** [Yuvaleros/material-ui-dropzone#164]
### Describe the bug
Seems like the documentation with regard to theming is out of date

### Steps to reproduce
 
```
import React, { Component } from 'react';
import { DropzoneArea } from 'material-ui-dropzone';
import { withStyles } from '@material-ui/styles';

const style = (theme) => (
  {
    dropzoneAreaRoot: {
      background: 'purple',
    },
  }
);

const DropAreaComponent = ({classes}) => (
      <DropzoneArea
        classes={{ root: classes.dropzoneAreaRoot }}
      />
);
export default withStyles(style)(DropAreaComponent);
```
-->

### Expected behavior
Given the documentation [here ](https://github.com/Yuvaleros/material-ui-dropzone/blob/master/docs/theming.md), I expect a nice looking dropzone, with styles applied to the root container. 

I get this error:
```
Material-UI: the key `root` provided to the classes prop is not implemented in DropzoneArea.
You can only override one of the following: dropZone,stripes,rejectStripes,dropzoneTextStyle,uploadIconSize,dropzoneParagraph
```
Of course, these classes work.

**Comment by panz3r** [comment]
Hi @wvanooijen92 ,

Thanks for your feedback, actually the docs is up to date but the changes are yet to be published to npm (they'll get released as version `3.1.0`), for now if you need to upgrade you can install the module directly from `GitHub`

for release `v3.x`
```shell
❯ npm i yuvaleros/material-ui-dropzone#84c7225
```
(the same also works with `yarn`)

for release `v2.x`
```shell
❯ npm i yuvaleros/material-ui-dropzone#7f3ac98
```

To see the differences between the 2 version see the [CHANGELOG](https://github.com/Yuvaleros/material-ui-dropzone/blob/master/CHANGELOG.md).

Thanks for your feedback and patience.
