### ISSUE TITLE
Improve Preview section

### ISSUE THREAD

**Issue by panz3r** [Yuvaleros/material-ui-dropzone#166]
### Describe the problem related to this feature request

Following the latest opened issues, I decided to open an "umbrella" issue to include all the feature requests, ideas and feedbacks related to the "Preview" section of `material-ui-dropzone`.

### Describe the solution you'd like

The updated implementation will have to follow this requirements:

- SHOULD better follow Material Design guidelines
- SHOULD be customisable by the user - see #160
- Its position SHOULD be controllable by using a single prop `previewType` (instead of relying on a combination of `showPreviews` and `showPreviewsInDropzone` props, to be deprecated) - see #130 
- SHOULD NOT present spacing and responsiveness issues - see #145, #146 and #165
- MIGHT have a better behaviour in case of a single file - see #130

**Comment by max-carroll** [comment]
I would like to see better behaviour for when the file limit is one, for instance this would be if the user is uploading just one file (document, video, pdf, or image) in that case we would probably want the image to take up the entire width if the dropzone is small or perhaps centre if its large, will chip in with the development of this, sorry its just I havent had any extra time this week

**Comment by usoni11** [comment]
I am trying to place the preview in centre of the dropzone with increased width and height ( as compare to the current size ) and hiding the upload icon as well as the dropzone text when the preview appears. Is that something achievable here?

**Comment by max-carroll** [comment]
Is this in the scenario of single file mode? If so then I would also find
that desirable?

**Comment by max-carroll** [comment]
as for with  #145, #146 and #165 I make the following recommendations 

* investigate whether the overflow: hidden is causing a scroll bar in some situations and if it is fix by getting rid of the spacing issue, it seems to cause more problems that it solves, the developer can always pass in the spacing they want but it seems a bit mad to default to something that's going to look terrible on small devices and cause that rubber band issue in other times,

**Comment by max-carroll** [comment]
> * SHOULD better follow Material Design guidelines

I have tried looking up the material design guidelines for drop zones, there doesn't appear to be any, can anyone find anything?

**Comment by panz3r** [comment]
> > * SHOULD better follow Material Design guidelines
> 
> I have tried looking up the material design guidelines for drop zones, there doesn't appear to be any, can anyone find anything?

Unfortunately there's no official design for a dropzone in the Material Design specs, possible approaches are the following:

- https://demo.geekslabs.com/materialize-v1.0/form-file-uploads.html
- The Material Design specs state that the recommended way to display lists of images is by using an [`Image List`](https://www.material.io/components/image-lists) and Material-UI provides a related component [`Grid List`](https://material-ui.com/components/grid-list/) which I'd suggest to use in the horizontal scrolling mode

**Comment by max-carroll** [comment]
Yes I like the look of that behaviour,  one more thing though,

Are we planning to move towards hooks and functional components?

If so should we try to do that before we rewrite the preview list?

Or do you think we should rewrite the preview list then rewrite everything
in functional components and hooks?

**Comment by panz3r** [comment]
> Yes I like the look of that behaviour, one more thing though,
Are we planning to move towards hooks and functional components?

I think that we should definitely move towards that goal.

> If so should we try to do that before we rewrite the preview list? Or do you think we should rewrite the preview list then rewrite everything in functional components and hooks?

For now I think that it's best if we try to only work inside the `Preview` component (which is already a functional one) and later adapt it if needed, of course we can use hooks on the `master` branch (since `v3.x` has a dependency which requires them), the only downside would be a not backportable solution to `v2.x` (which I suppose we'll sunset sooner rather than later).

**Comment by max-carroll** [comment]
@panz3r , I've just started working on this

**Comment by max-carroll** [comment]
![image](https://user-images.githubusercontent.com/13512675/82382084-46c3ee80-9a23-11ea-94db-ba2246ac6bcc.png)

> Its position SHOULD be controllable by using a single prop previewType (instead of relying on a combination of showPreviews and showPreviewsInDropzone props, to be deprecated) - see #130

which props did we want to deprecate, I'm assuming `previewChipProps` and `previewGridProps` in favour of something which allows us to customise the things without a load of complicated props?

**Comment by panz3r** [comment]
> ![image](https://user-images.githubusercontent.com/13512675/82382084-46c3ee80-9a23-11ea-94db-ba2246ac6bcc.png)
> 
> > Its position SHOULD be controllable by using a single prop previewType (instead of relying on a combination of showPreviews and showPreviewsInDropzone props, to be deprecated) - see #130
> 
> which props did we want to deprecate, I'm assuming `previewChipProps` and `previewGridProps` in favour of something which allows us to customise the things without a load of complicated props?

The props to be deprecated are `showPreviews` and `showPreviewsInDropzone`, I'd replace them with something like `previewType` with values like `none`, `inside` (default) and `below`.

The 2 props you are referring to are used to customise the Mui components used inside the Preview section (maybe we can remove the `previewGridProps` one if we'll no longer have a `Grid` 😬 ).

**Comment by max-carroll** [comment]
It would appear that material-ui have an implementation of the image list https://material-ui.com/components/grid-list/ so I will utilise this

**Comment by max-carroll** [comment]
Hi there @panz3r, this is probably painfully obvious, but just a heads up in case, that this work is going to be a considerable rework of the PreviewList.js file and therefore would be extremely cautious about any parallel development on this file

**Comment by max-carroll** [comment]
I'm halfway through experimenting at the moment, I've made a video of how I've got it behaving thus far if anyone wants to contribute feedback https://www.loom.com/share/1edf037829614f3fa4f77b7888fadf8b

**Comment by panz3r** [comment]
@max-carroll Thanks a lot for sharing your progress, looks really good so far and I personally like it more than the current implementation .

Keep it up!! 👍 👍

**Comment by max-carroll** [comment]
progress update 2  https://www.loom.com/share/55fd99ae1e404870a9eb08f2b7e906bd

I have ensured that we can customise it as much as possible, I've just got a few aesthetic issues to sort out

* behaviour of the "Drop files here" message and icon when files are selected
* styling of the remove button

Ill fix these and then send a PR, I might update the DropzoneArea.MD a little bit to fully showcase what we can do to customize the preview list

**Comment by Thromind859** [comment]
It would be interesting to be able to actually open the files. Image previews are fine but how about other types of files? If I add a PDF file I can't open it. Would like to know if it would be possible to open it in a new tab, for example. 

Currently, when I click on the files preview when they are inside the dropzone, it opens the file chooser. I have to right-click images and click 'open in new tab'. And that only works for images. If the preview is outside the dropzone, clicking on any file simply does nothing.

**Comment by jpainam** [comment]
any feedback progress with this issue? the current version still has the same preview.

**Comment by max-carroll** [comment]
This has been implemented however don't think this has been deployed to NPM yet, however if your super desperate (as I was) you can reference a link to the branch rather than using npm,  by using this `yarn add <git remote url>#<branch/commit/tag>` so this would be `yarn add https://github.com/Yuvaleros/material-ui-dropzone.git#v4.x` the syntax is also similar if your using npm

**Comment by jpainam** [comment]
@max-carroll  thanks, it worked. I have this `warning`
```javascript
Warning: React does not recognize the `justifyContent` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `justifycontent` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by ForwardRef(Grid))
    in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
    in WithStyles(ForwardRef(Grid)) (created by Dropzone)
    in div (created by Dropzone)
    in Dropzone (created by DropzoneAreaBase)
    in DropzoneAreaBase (created by WithStyles(DropzoneAreaBase))
    in WithStyles(DropzoneAreaBase) (created by DropzoneArea)
    in DropzoneArea (at DropUploadImages.js:5)
    in DropUploadImages (at MyCompomentDropUpload.js:227)
```

**Comment by max-carroll** [comment]
Oh right yes, I'm having a look at the code now it appears that we are using justifyContent instead of simple justify on a Grid component, this shouldn't have any undesired effect on your page just an error in your console, we're basically just passing a component a prop it doesn't accept

**Comment by jpainam** [comment]
yes; you are right, I'm logging a lot of info in my console and wanted to get rid of any warnings. It doesn't affect my page though. i'll clone the v4 and fix it on my repo

**Comment by max-carroll** [comment]
Ah awesome, could you create a pull request? 😉

**Comment by jpainam** [comment]
done!!
