### ISSUE TITLE
inputProps not working when setting files prop to an array of files

### ISSUE THREAD

**Issue by OmarZidan1997** [Yuvaleros/material-ui-dropzone#167]
### ISSUE
I have with inputProps on DropzoneArea. I checked the documentation of how i can use it and i followed as specified but it does still not work. Im trying to upload image and it shows on the preview section but Im using stepper form which means when i procceed to the next step and go back to the previous, my uploaded image on the preview section is gone.

below is my code
```
          <DropzoneArea
          dropzoneClass={classes.uploadImageDropZone}
            open={openImageDialog}
            acceptedFiles={["image/*"]}
            showPreviews={true}
            showPreviewsInDropzone={false}
            cancelButtonText={"cancel"}
            submitButtonText={"submit"}
            filesLimit={1}
            // initialFiles={[]}
            onChange={handleImage}
            onClose={(e) => {
              setOpenImageDialog(false);
            }}

            inputProps={{
              files: values.imageFile
            }}
          />
```
values.imageFile is an array of File objects.

any suggestion of how i can solve this problem?

**Comment by panz3r** [comment]
Hi @OmarZidan1997 ,

Thanks for your feedback, unfortunately at the moment what you're trying to achieve is not possibile, you can however try using the `initialFiles` props but that behaves a little bit differently.

See issue #75 for more details on how we'll try to tackle this kind of issues.
