### ISSUE TITLE
Failed prop type: Invalid prop `showAlerts` of value `true` supplied to `DropzoneAreaBase`

### ISSUE THREAD

**Issue by travelrus** [Yuvaleros/material-ui-dropzone#180]
### Describe the bug

Get the following error in my console:
Invalid prop `showAlerts` of value `true` supplied to `DropzoneAreaBase`, expected one of [null,null].

It doesn't matter was the specific value to 'showAlerts' set or not. I tried as Boolean values so an array according to your documentation. 

### Steps to reproduce

  1. Import dropzoneAreaBase
  2. Use it.

### Expected behavior

showAlerts except values accoding to documentation and doesn't fire an error in console if everything is ok

### Screenshots

![image](https://user-images.githubusercontent.com/56366516/83263050-a5792d00-a1c6-11ea-8110-92b2d84fc284.png)
![image](https://user-images.githubusercontent.com/56366516/83263081-b3c74900-a1c6-11ea-845f-d2df8d4052c2.png)

### Versions

- OS: Windows 10
- Browser: Chrome
- `@material-ui/core` version: [4.9.14]
- `material-ui-dropzone` version: [github:yuvaleros/material-ui-dropzone#4fda0ea]

### Additional context

please take a look at the attached file. Found duplicate in your code base
![image](https://user-images.githubusercontent.com/56366516/83262919-69de6300-a1c6-11ea-94e0-8ce54f3e107f.png)

**Comment by panz3r** [comment]
Hi @travelrus ,

Thanks for your feedback, I just pushed the fixes for the issues you reported.

You can install the updated module directly from `GitHub`

```shell
❯ npm i yuvaleros/material-ui-dropzone#2ffcbb7
```

(the same also works with `yarn`)

Let me know if it works as expected.

**Comment by travelrus** [comment]
@panz3r ,  thanks a lot. I tried a source you mentioned. Seems like a bug I reported is not reproducing any more.
