### ISSUE TITLE
3.2.0 not available on NPM

### ISSUE THREAD

**Issue by senser1** [Yuvaleros/material-ui-dropzone#188]
Release 3.2.0 does not seem to be available on NPM yet..

**Comment by panz3r** [comment]
Hi @senser1 ,

Actually version `3.2.0` was wrongly published to NPM as version `3.1.0` 😅 , unfortunately that version includes wrong TS typings so it's causing some issues (see #172 and #184 ).

A fix has been pushed to `master` and will be published as version `3.2.1`.

**Comment by senser1** [comment]
Thanks, will wait for 3.2.1 to be available then. :)
