### ISSUE TITLE
Migrate to Functional components and hooks

### ISSUE THREAD

**Issue by panz3r** [Yuvaleros/material-ui-dropzone#197]
## Task

With version 4.x having a minimum dependency on `React 16.8` we can now rewrite all of the module code to take full advantage of `Hooks` and simplify the internal code.

**Comment by max-carroll** [comment]
@panz3r , I am part way through this, should hopefully have a pull request ready this week some time

**Comment by max-carroll** [comment]
I'm working on this again today sorry for delay

**Comment by max-carroll** [comment]
@panz3r , in PreviewList we destructure all the props together in the declaration of the function, however in other places we do it as and when they are required, I assumed we wanted to go the way of destructuring the props in the declaration, but just thought I would double check before I create pull request

* destructuring props in function brackets, e.g. `const myComponent = ({some, of, the, props})`
* destructuring as and when props or required like this `const myComponent = (props) => ` and then later on ` const {subset, of, props} = props

**Comment by panz3r** [comment]
Hi @max-carroll ,

I’d go with destructuring in the initial declaration to have all the props always available and to keep the definitions clearer.

👍

**Comment by max-carroll** [comment]
@panz3r  Pull request ready for review 🕵️‍♀️
