### ISSUE TITLE
would love to see a @material-ui (v1.x) port of this component

### ISSUE THREAD

**Issue by logemann** [Yuvaleros/material-ui-dropzone#2]

**Comment by javierseixas** [comment]
Check here https://github.com/rockie/material-ui-dropzone

**Comment by Yuvaleros** [comment]
Hi,
Sorry I didn't really have the time to update the component.
I saw a few good looking forks that use material-ui v1 either that or a PR would also be welcomed. :)

**Comment by Yuvaleros** [comment]
Lib was updated to latest material-ui version.
