### ISSUE TITLE
clearOnUnmount doesn't work for functional components.

### ISSUE THREAD

**Issue by mfaizan1** [Yuvaleros/material-ui-dropzone#203]
### Describe the bug
I have a drop zone in a functional component, when form is submitted successfully, i clear state values and selected images arrays, but images are still visible in dropzone previews

i also used clearOnUnmount as mentioned in this issue
[Clear file list when submitting not working](https://github.com/Yuvaleros/material-ui-dropzone/issues/141)

### Expected behavior

selected files should be cleared

### Versions

- Browser: [e.g. chrome, safari]
- `@material-ui/core` version: [e.g. 4.9.9]
- `material-ui-dropzone` version: [e.g. 2.4.9]

**Comment by panz3r** [comment]
Hi @mfaizan1 ,

Thanks for your feedback, which version of `material-ui-dropzone` are you using?

For your use-case I'd suggest you to use `DropzoneAreaBase` component which allows you more control over the files state.

It's not yet publish to `npm` but you can install it by running

```shell
❯ npm i yuvaleros/material-ui-dropzone#v3.2.1
```

(the same also works with `yarn add`)

See [docs](https://yuvaleros.github.io/material-ui-dropzone/#dropzoneareabase) for more details.

**Comment by mfaizan1** [comment]
@panz3r i am using v2.4.9, ok Thanks i will have a look

**Comment by alpgokcek** [comment]
I have the same problem with version ^3.3.0. I tried the package you shared as well but I still get the same error.

error message:
index.js:1 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in DropzoneDialog (at edit/index.js:213)
    in div (created by ForwardRef(Grid))
    in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
    in WithStyles(ForwardRef(Grid)) (at edit/index.js:209)
    in div (created by ForwardRef(Grid))
    in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
    in WithStyles(ForwardRef(Grid)) (at edit/index.js:169)
    in div (at edit/index.js:168)
    in div (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (at edit/index.js:164)
    in div (at edit/index.js:163)
    in div (at edit/index.js:159)
    in EditBrand (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in withRouter(Connect(EditBrand)) (at restrictedRoute/index.js:17)

**Comment by alpgokcek** [comment]
By the way, I fixed this issue by using [this](https://github.com/material-components/material-components-web-react/issues/434#issuecomment-449561024) logic, but I honestly think that this problem should be fixed as soon as possible.

**Comment by ramakrishna449** [comment]
hi @panz3r 
i need to clear my DropzoneArea after form submitting 
gone through clearOnUnmount  props but  it will not worked ...please help me ..
i used this version of  "material-ui-dropzone": "^3.5.0",

 <DropzoneArea
                       acceptedFiles={['image/jpeg', 'image/png', '.PDF','.xls','.xlsx', '.txt', '.csv', '.doc', '.docx']}
                       maxFileSize={5000000}
                       filesLimit ={10}
                       onChange={e => setUpload(e)}
                       showFileNames={true}
                       dropzoneText={"Drag file(s) here,or browse"}
                       clearOnUnmount={true}
                       />
