### ISSUE TITLE
Remove icon is not visible when image aligns with right border.

### ISSUE THREAD

**Issue by trashhead** [Yuvaleros/material-ui-dropzone#209]
### Describe the bug

If adding files so that it spans the whole row the rightmost element's remove icon is outside the container, thus it is not visible nor clickable.

### Steps to reproduce

1. Go to the demo page and scroll down to basic usage (https://yuvaleros.github.io/material-ui-dropzone/).
2. Add three images.
3. See that when hovering the file farthest to the right its delete icon is not visible.

### Expected behavior

Expected behaviour would be that the icon appears to the left instead of right if it cant fit.

### Versions

- OS: [e.g. windows]
- Browser: [e.g. chrome]
- `@material-ui/core` version: [e.g. 4.9.13]
- `material-ui-dropzone` version: [e.g. 3.3.0]

![image](https://user-images.githubusercontent.com/1001457/85850556-51ee0500-b7ad-11ea-8bec-8a507da20d65.png)

**Comment by panz3r** [comment]
This issue will be resolved with the release of `v4.x` and the new preview section (see #166  )
