### ISSUE TITLE
Possibility to change text in alerts

### ISSUE THREAD

**Issue by hrafaelveloso** [Yuvaleros/material-ui-dropzone#21]
Hi!

I really like this Dropzone, and the alerts are just awesome! However, it should be possible to change the text that appears inside each alert type.

Is that possible?

**Comment by qlecler** [comment]
Would be nice to have this

**Comment by widomin** [comment]
You can..
Like this:
<DropzoneArea 
    getFileLimitExceedMessage={ () => "Solo puedes adjuntar 1 archivo"} 
/>

**Comment by hrafaelveloso** [comment]
I can now in the new release, docs been updated 9 days ago. Thanks

**Comment by widomin** [comment]
> I can now in the new release, docs been updated 9 days ago. Thanks

Ok, sorry.. is the first time I use it.
