### ISSUE TITLE
extra props to initialFiles

### ISSUE THREAD

**Issue by Alarees** [Yuvaleros/material-ui-dropzone#210]
### adding extra props to initialFiles

when you having images loaded from api, you may want to delete that image, so you need the image id to delete it from database 

### the solution that i suggest

set `initialFiles` lika this 
```
[
   {
      url:'imageUrl',
      //user extra props
   }
]
```

**Comment by bodas80** [comment]
This is a must-have feature. Makes this package unusable :(

**Comment by bodas80** [comment]
Nvm, I found #194 pull request that explains how to load images from urls instead of creating files. I wish It would state something about it in documentation, would save a huge chunk of time for those like me out there.
