### ISSUE TITLE
Make `onChange` function potentially asynchronous

### ISSUE THREAD

**Issue by wowczarczyk** [Yuvaleros/material-ui-dropzone#212]
### Describe the problem related to this feature request

`onChange` should potentially be async and handled that way 

### Describe the solution you'd like

This library could await until onChange resolves and display its alerts when the processing is done

**Comment by panz3r** [comment]
Hi @wowczarczyk,

Thanks for feedback, whilst I understand the change you are requesting, I'd like to know more about your use-case, in particular what are you trying to achieve? and how having `onChange` async would help you?

**Comment by wowczarczyk** [comment]
I wanted to show the snackbar message after the file was actually uploaded, but found another way of dealing with this situation so I am all good with closing this issue
