### ISSUE TITLE
Docx files filtered out (but still allowed) accepting "application/*"

### ISSUE THREAD

**Issue by FilipeCosta06** [Yuvaleros/material-ui-dropzone#214]
### Describe the bug
_There is also a question/feature request at the end (if I don't forget)_
`.docx` file hidden in input even though I am setting `acceptedFiles={["application/*", "audio/*", "image/*", "text/*", "multipart/*", "video/*"]}`.

According to [MDN's common MIME types](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types) page, a Word document `.docx` file has `application/vnd.openxmlformats-officedocument.wordprocessingml.document` as MIME type
![image](https://user-images.githubusercontent.com/25252573/87796193-51dfa300-c849-11ea-8b3d-0892cee717cd.png)

### Steps to reproduce
1. Create a `DropzoneArea`
2. Set `acceptedFiles={["application/*", "audio/*", "image/*", "text/*", "multipart/*", "video/*"]}`
3. Click the input and try to add a `.docx` file
4. Such files won't show up and you will have to manually set the input's filter to `"*"` to display any `.docx` in the current folder

### Expected behavior
Since a `.docx` file has a MIME type matching `application/*`, I expected it to be visible while opening the input.

Please note that adding a `.docx` file is allowed, it's just that the input's initial "filter" will hide it.
Below you can find the generated input:
```
<input accept="application/*,audio/*,image/*,text/*,multipart/*,video/*" multiple="" type="file" autocomplete="off" tabindex="-1" style="display: none;">
```
This is looking like a Chrome or OS issue and, as such, I am simply gonna allow all types using `acceptedFiles={[]}`. 

Also, here's my "request" _(booyah, didn't forget)_:
Please update the doc to explicitly state that `acceptedFiles={[]}` is the way to accept all types (turns into `<input accept multiple />`). Or even make it the default value :D

I just spent more time than I'd like to admit find this solution ahah. I got the hint from reading the react-dropzone's doc (**_by providing_** implies it's optional and doesn't necessarily have a default value) while this repo's doc including a default value jebaited me hard ^^ I initially tried setting `"*"` as a value but that would display the files in the input but not accept the selected (snack/toast error saying the type wasn't allowed), but this was expected since it didn't not respect the rules defined below.

> By providing accept prop you can make the dropzone accept specific file types and reject the others.
> 
> The value must be a comma-separated list of unique content type specifiers:
> 
> A file extension starting with the STOP character (U+002E). (e.g. .jpg, .png, .doc).
> A valid MIME type with no extensions.
> audio/* representing sound files.
> video/* representing video files.
> image/* representing image files.

### Versions

- OS: Windows 10 x64
- Browser: chrome
- `@material-ui/core` version: "^4.9.13"
- `material-ui-dropzone` version: "^3.3.0"

Request aside, as I mentioned, this may not be an issue related to this library. I'm posting it here just in case I'm wrong (could be my OS is mismatching MIME types and file extensions ? meh)

**Comment by panz3r** [comment]
Hi @FilipeCosta06 ,

Thanks for your detailed feedback, as it is this is a long standing question and partly depends on the module used under the hood by `material-ui-dropzone` (which is [`react-dropzone`](https://react-dropzone.js.org) btw) and a related issue about MIME types (issue [#276](https://github.com/react-dropzone/react-dropzone/issues/276)).

> Please update the doc to explicitly state that acceptedFiles={[]} is the way to accept all types (turns into <input accept multiple />). Or even make it the default value :D

I can agree with you on this, changing the default would make sense to allow dropping all types of file.
