### ISSUE TITLE
Delete preview is not working in DropzoneDialogBase.

### ISSUE THREAD

**Issue by sanjays442** [Yuvaleros/material-ui-dropzone#216]
Delete preview is not working in DropzoneDialogBase.

**Comment by panz3r** [comment]
Hi @sanjays442 ,

Thanks for your feedback, can you provide a bit more context about this issue? can you please share the part of code where you are using `DropzoneDialogBase`?

**Comment by sanjays442** [comment]
<DropzoneDialogBase
              acceptedFiles={['image/*']}
              fileObjects={fileObjects}
              cancelButtonText={"cancel"}
              submitButtonText={"submit"}
              maxFileSize={5000000}
              filesLimit="100"
              open={open}
              onAdd={newFileObjs => {
                console.log('onAdd', newFileObjs);
                setFileObjects([].concat(fileObjects, newFileObjs));
              }}
              onDelete={deleteFileObj => {
                console.log('onDelete', deleteFileObj);
              }}
              onClose={() => setOpen(false)}
              onSave={() => {
                getImages(fileObjects);
                setOpen(false);
              }}
              showPreviews={true}
              showFileNamesInPreview={true}
            />

This is my code and also you can check in your reference site https://yuvaleros.github.io/material-ui-dropzone/. It is also not working here.

**Comment by panz3r** [comment]
Hi @sanjays442 ,

As it is the `onDelete` is implemented to only log the removed file, to actually remove it from the state you should write the required logic, the simplest implementation would be 

```jsx
onDelete={(deletedFileObj, removedIdx) => {
  console.log('onDelete', deleteFileObj);
  setFileObjects(currentFiles => currentFiles.filter((file, idx) => idx !== removedIdx));
}}
```

in the sample this logic is not implemented since it depends strictly on your use-case, the implementation I proposed above is a general purpose one but it might not be the right one for you.

**Comment by sanjays442** [comment]
Thank you worked
