### ISSUE TITLE
File is not defined on 3.3.0

### ISSUE THREAD

**Issue by bbourn** [Yuvaleros/material-ui-dropzone#218]
### Describe the bug

I get this reference error  when  I use the latest version of this package (3.3.0) instead of 3.2.1

```
ReferenceError: File is not defined
    at Object.<anonymous> (./node_modules/material-ui-dropzone/dist/index.js:1166:77)
```

### Steps to reproduce

Load my app that simply imports from material-ui-dropzone and instantly get above error.

### Expected behavior

Package to have File defined.

### Versions

- OS: macOS
- Browser: chrome
- `@material-ui/core` version: 4.11.0
- `material-ui-dropzone` version: 3.3.0

**Comment by cayasso** [comment]
Getting this same error with same version

**Comment by cayasso** [comment]
Ok it looks like this is already fixed here https://github.com/Yuvaleros/material-ui-dropzone/issues/208 but 3.3.1 is not published yet to NPM.

**Comment by panz3r** [comment]
hi @cayasso ,

Thanks for your feedback, as of July 24 version `3.3.1` is available on NPM.
