### ISSUE TITLE
Custom Icon ignored

### ISSUE THREAD

**Issue by GiacomoGranzotto** [Yuvaleros/material-ui-dropzone#236]
### Describe the bug

Can not change the icon from the dragndrop zone.

### Steps to reproduce

Tried use the example below:

```
import { AttachFile } from '@material-ui/icons';

<DropzoneAreaBase
  Icon={AttachFile}
  dropzoneText={"Drag and drop an image here or click"}
  onChange={(files) => console.log('Files:', files)}
  onAlert={(message, variant) => console.log(`${variant}: ${message}`)}
/>
```

### Expected behavior

The icon from the dropzone should be changed to AttachFile 

### Versions

"@material-ui/core": "4.9.14",
"material-ui-dropzone": "^3.3.1",
"react": "^16.12.0",

**Comment by panz3r** [comment]
Hi @GiacomoGranzotto ,

Thanks for your feedback, custom Icon support is available as of version `3.4.0` of the module which is currently not published to npm.

In the meanwhile to install the latest version you can use

```shell
❯ npm i yuvaleros/material-ui-dropzone#ab6210f
```
(the same also works with `yarn`)

**Comment by GiacomoGranzotto** [comment]
Thank you very much!

**Comment by panz3r** [comment]
version `3.4.0` has been published to `npm`
