### ISSUE TITLE
Is there a way to download a file?

### ISSUE THREAD

**Issue by asifkabani** [Yuvaleros/material-ui-dropzone#241]
## Feature Request
Ability to download the loaded files.

### Describe the problem related to this feature request
Currently I am using the chip preview. The chip UI shows a close icon, but no way to download the file itself when you click on it.

### Describe the solution you'd like
Some way of being able to download the loaded file. So something like a download icon next to the close icon.

### Describe alternatives you've considered
None

### Teachability, Documentation, Adoption, Migration Strategy
User can click on downloaded files by clicking on an icon to download the file to see what it is.

### Additional context
![image](https://user-images.githubusercontent.com/9083341/92506260-cb9d6880-f1ca-11ea-85b3-2fca5164a636.png)

**Comment by tommiCZE** [comment]
hi,
I have the same problem. I wanted to ask what is the solution?
