### ISSUE TITLE
AcceptedFiles shown as rejected but still working

### ISSUE THREAD

**Issue by arthurliebhardt** [Yuvaleros/material-ui-dropzone#253]
### Describe the bug
When I limit the accepted Files like following
`acceptedFiles={['.mp3','.m4a','.mp4','.wav','.ts','.mka','.mov']}`

Dropzone shows the red reject effect but the rest works fine. My question would be how I can get rid of the red reject effect?

### Versions

- OS: Mac
- Browser: chrome
- `@material-ui/core` version: 4.10.1
- `material-ui-dropzone` version: 3.5.0

**Comment by zoebisch** [comment]
I ran into the same issue, this was the last I saw on the issue: [](https://github.com/Yuvaleros/material-ui-dropzone/issues/141)
the suggestion being to use `disableRejectionFeedback`. 

I am trying to use a hook to accomplish this but am not sure yet how to approach the problem I am thinking something like interacting directly with dropzone `onDrag `or something, because it's a catch-22 type of problem. Disabling the feedback does just that, so no more red bars when dragging an invalid type not found in `acceptedFiles`. I am sure there is a way, I haven't figured it out yet.

**Comment by zoebisch** [comment]
I know what this may be. I realized this in my project.

You may need to do something like: 
`acceptedFiles={['video/mp3','video/m4a','video/mp4','video/wav','video/ts','video/mka','video/mov']}`

**Comment by zoebisch** [comment]
After dealing with this a bit more, here is what seems to happen. If you do not pass the correct MIME type you will not have functional red bars on the drag-and-drop feature. If you follow the [guide here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types), it seems to cover most types correctly, at least on those which I have tested. 

I have found that 'application/rtf' does not work correctly but using 'text/srt' does. I would imagine an issue in the core component of Dropzone is the underlying issue but don't have time to confirm. 

What I would request is way to handle files which are not covered under the mime types and prevent red drag-and drop bars, a good example is `.srt` files which are essentially plain text files of audio translations if I am not mistaken. So there are some odd issues which potentially would need to be custom handled on the drag. This seems it would be a bit of work to do and to keep the component reusable without adding a bit of extra logic.

**Comment by arthurliebhardt** [comment]
Sorry, didn't saw your replies. Actually for me the following solution

` acceptedFiles={[[
                    'audio/mpeg',
                    'audio/m4a,',
                    'audio/x-m4a',
                    'video/mp4',
                    'audio/wav',
                    'video/quicktime,',
                    'audio/x-matroska',
                    'video/x-matroska',
                    '.mka',
                    'audio/tsplayer',
                    '.ts',
                  ]]}`
