### ISSUE TITLE
Getting filenames to show up in preview

### ISSUE THREAD

**Issue by mmerali96** [Yuvaleros/material-ui-dropzone#26]
Hi, I am trying to get the file names to show up in the preview. I set the prop showFileNamesInPreview=true inside <DropzoneDialog /> and <DropzoneArea /> but the names do not show up. The files imported are txt and pdf files.

Thanks in advance

**Comment by Yuvaleros** [comment]
Changed the documentation - it's showFileNamesInPreview=true

**Comment by mmerali96** [comment]
Thanks, I was able to get it working. Closing this issue.
