### ISSUE TITLE
When the file size is too large error says it is wrong type

### ISSUE THREAD

**Issue by CorayThan** [Yuvaleros/material-ui-dropzone#30]
The error for when the file size is too large is confusing, because it says it is the wrong type, when really it's too large.

**Comment by xiaoxinsun** [comment]
I've got the same issue. The only happens when wildcard is used in acceptedFiles.

**Comment by IsabellaRey** [comment]
I see something slightly different. I've got acceptedFiles={['image/png']} and the error for file too big simply says "File xxx was rejected" but doesn't tell me why

**Comment by carloslfu** [comment]
Hi @CorayThan and @xiaoxinsun, please provide a [CodeSanbox](https://codesandbox.io) or a code example of this, maybe is related to #47.

**Comment by carloslfu** [comment]
I think @IsabellaRey issue is related to #47.

**Comment by Cammac7** [comment]
I've got the same issue

**Comment by Yuvaleros** [comment]
@Cammac7 I can't seem to reproduce the issue. Could you please update to the latest version, this might be solved by #47 like @carloslfu mentioned. If it does happen again, please provide a code snippet.

**Comment by panz3r** [comment]
Closing issue as it is stale.

If this issue is still relevant, please upgrade to the latest version of `material-ui-dropzone` and open a new one with updated details.

Thanks for your feedbacks.
