### ISSUE TITLE
Should be using Typography instead of <p></p>

### ISSUE THREAD

**Issue by PolGuixe** [Yuvaleros/material-ui-dropzone#31]
As the library already uses Material-UI I would make use of the `<Typography/>` component for texts to make sure it works well with the current's app `theme`.

**Comment by IsabellaRey** [comment]
This includes the text for displaying the filename

**Comment by panz3r** [comment]
Hi @PolGuixe and @IsabellaRey ,

Suggested changes are already on master (see PR #121 ) and will be on v2.x (see PR #132 ).

Closing this issue for now, let me know if you find any other problem related to this issue.
