### ISSUE TITLE
Possibility to change texts in DropzoneDialog (title, dropzonetext and button captions)

### ISSUE THREAD

**Issue by skalma** [Yuvaleros/material-ui-dropzone#32]
When using the dropzonearea the property dropzonetext is available. For the dialog it should be possible to adapt dropzonetext, dialogtitle and buttoncaptions.

**Comment by Yuvaleros** [comment]
@skalma Don't know If it's still relevant but the dropzonetext and dialogtitle exist but were just missing from the README - I added them.

buttoncaptions are now also configurable and can be found in the README as well.

**Comment by eluchsinger** [comment]
@Yuvaleros And why not include the rest of the texts? I need to translate them somehow.
