### ISSUE TITLE
ZIP upload working on UNIX systems but not on Windows

### ISSUE THREAD

**Issue by ghost** [Yuvaleros/material-ui-dropzone#321]
### Describe the bug
This could well be a mistake made by us somewhere. In our application we use this uploader for ZIP files, and on OSX everything is working as expected, but on Windows devices (any browser) we keep receiving the message 'File not supported'.

This is on any browser on both operating systems.

### Steps to reproduce

```
    acceptedFiles = ['application/zip'],
    maxFileSize = 150000000, // 150mb

   ...

    <DropzoneDialog
      {...register(name)}
      acceptedFiles={acceptedFiles}
      filesLimit={1}
      maxFileSize={maxFileSize}
      initialFiles={initialFiles}
      showPreviewsInDropzone={false}
      open={isOpen}
      onSave={onDropzoneSave}
      onClose={onDropzoneClose}
    />
```

### Expected behavior

We expect this to work on all operating systems. 

### Screenshots

![image-20210823-141901 (1)](https://user-images.githubusercontent.com/51475496/131089112-11df3e99-c752-489e-8990-d385adae1e02.png)

**Comment by dahem** [comment]
add '.zip' in acceptedFiles

**Comment by ghost** [comment]
Closing because it can't be reproduced by me anymore.
