### ISSUE TITLE
dropzoneText does not work in DropzoneArea

### ISSUE THREAD

**Issue by talamanpat** [Yuvaleros/material-ui-dropzone#33]
Hi! Great component.
Just, it does not change the name of the dropzoneArea:

          <DropzoneArea
            dropzoneText={'Upload files.'}
             .....
I have tried with brackets, without, etc... It does not change :D 
Any help is very welcome, as well as this awesome tool.

**Comment by Yuvaleros** [comment]
You are correct, it's an issue with dropzoneText on DropzoneArea.
FIxed on version 3.2.4
