### ISSUE TITLE
missing types for styling props

### ISSUE THREAD

**Issue by qlecler** [Yuvaleros/material-ui-dropzone#34]
Hello there !

It seems the interface for DropzoneArea is missing some styling props :

`export interface DropzoneAreaProps {
    acceptedFiles?: string[];
    filesLimit?: number;
    maxFileSize?: number;
    dropzoneText?: string;
    showPreviews?: boolean;
    showPreviewsInDropzone?: boolean;
    showFileNamesInPreview?: boolean;
    showAlerts?: boolean;
    clearOnUnmount?: boolean;
    onChange?: (files: any) => void;
    onDrop?: (files: any) => void;
    onDropRejected?: (files: any, evt: any) => void;
    onDelete?: (file: any) => void;
}`

props I need :

`     <DropzoneArea
         ...
          dropZoneClass
...
dropzoneParagraphClass
...
        />`

Thanks 👍

**Comment by katyasafford** [comment]
I am also not able to use `dropZoneClass`. 

When I try to do `<DropzoneArea dropZoneClass="test" />`, Typescript gives me a similar error: `Type '{ dropZoneClass: string; }' is not assignable to type 'IntrinsicAttributes & DropzoneAreaProps & { children?: ReactNode; }'.
  Property 'dropZoneClass' does not exist on type 'IntrinsicAttributes & DropzoneAreaProps & { children?: ReactNode; }'.ts(2322)`

**Comment by peterchq** [comment]
i'm pretty sure it is meant to be **dropzoneClass** and not **dropZoneClass**

**Comment by tejasgrd** [comment]
Use it using Make Styles
`
import { makeStyles } from '@material-ui/core/styles';
const useStyles = makeStyles(() => {
	myDropZone: {
        position: 'relative',
        width: '100%',
        height: '40%',
        minHeight: '100px',
        backgroundColor: '#F0F0F0',
        border: 'dashed',
        borderColor: '#C8C8C8',
        cursor: 'pointer',
        boxSizing: 'border-box',
    },
}):


export const AudioModal = (props) => {
	
	const classes = useStyles();


	<DropzoneArea  showPreviews={false} showAlerts={false} dropzoneClass={classes.myDropZone} />

}


`

**Comment by tejasgrd** [comment]
dropzoneClass works as expected for me 
`
import { makeStyles } from '@material-ui/core/styles';
const useStyles = makeStyles(() => {
	myDropZone: {
        position: 'relative',
        width: '100%',
        height: '40%',
        minHeight: '100px',
        backgroundColor: '#F0F0F0',
        border: 'dashed',
        borderColor: '#C8C8C8',
        cursor: 'pointer',
        boxSizing: 'border-box',
    },
}):


export const AudioModal = (props) => {
	
	const classes = useStyles();


	<DropzoneArea  showPreviews={false} showAlerts={false} dropzoneClass={classes.myDropZone} />

}


`

**Comment by Yuvaleros** [comment]
Closing issue - seems like a typo.
