### ISSUE TITLE
Missing dependency for @material-ui/icons

### ISSUE THREAD

**Issue by accuware** [Yuvaleros/material-ui-dropzone#36]
`Module not found: Can't resolve '@material-ui/icons/CloudUpload`

Needs an additional `npm install @material-ui/icons --save` to resolve

**Comment by Yuvaleros** [comment]
I see that @material-ui/icons exists as a peer dep, I'll add it as a dependency.

**Comment by Yuvaleros** [comment]
Fixed in version 3.2.4

**Comment by accuware** [comment]
Thanks
