### ISSUE TITLE
Trigger DeleteHandler To Remove File From Dropzone Area

### ISSUE THREAD

**Issue by alirezakay** [Yuvaleros/material-ui-dropzone#38]
hey,
I really liked this component, thanks a lot...

Um,
I want to create my own **custom file preview** after each file's added to the dropzone area.
So, I need to define a new **deleteHanlder**

I absolutely know how to remove the file from **files array** 
but don't know how to **trigger** the Dropzone removeHandler to delete the file from the area

**Comment by alirezakay** [comment]
## I Found It 💯 

Well, there is a function in  **DropzoneArea** class, named: **handleRemove()**

---

To access this method from parent components, you must consider that, this module, uses `material-ui` and the default export is like:

> export default withStyles(styles)(DropzoneArea)


So, you'll need to access a **child** react **node** to access DropzoneArea class

I've found this approach:

- First: create a reference to the DropzoneArea component in your class
```js
.
.
dropzoneRef = react.createRef();
.
.
<DropzoneArea ref={this.dropzoneRef }>. . .</DropzoneArea>
```

- Second: call the **handleRemove** function of the referenced DropzoneArea component:
```js
deleteHanlder = (idx) => {
  // idx is the index of the file you wanna be removed from dropzone area 
  const e = {};
  e.stopPropagation = () => {}
  this.refDropZone.current._reactInternalFiber.child.stateNode.handleRemove(idx)(e);
}
```


### Notice
As I searched in the src files of this module, the `handleRemove` function, has a parameter that is the **index** of the file you want to be removed,
And the returned result is another function that gets an **event** as a parameter.
In the first line of the function, `stopPropagation` function of the event is called!

Because I had no event object on my own code, I created a fake event like `e`.
Then I added a fake function named: `stopPropagation`
This is just for **bypassing the errors**

**Comment by finalevil** [comment]
@alirezakay  
very useful~
thank you very much

**Comment by 1ragnar** [comment]
@alirezakay How did you manage to call ref on the component ?

**Comment by pouannes** [comment]
07/2020 update: I had to adapt the code above a bit (my code is for a functional component but you can adapt it):

```javascript
.
.
dropzoneRef = React.createRef();

const deleteHandler = (idx) => {
    // idx is the index of the file you wanna be removed from dropzone area
    e.stopPropagation = () => {};
    // file is the fileObject you want to delete
    dropzoneRef.current._reactInternalFiber.stateNode.deleteFile(file, idx);
  };
.
.
<DropzoneArea ref={dropzoneRef }>. . .</DropzoneArea>
```
