### ISSUE TITLE
how to change the height

### ISSUE THREAD

**Issue by samithahansaka** [Yuvaleros/material-ui-dropzone#39]

**Comment by TerjeNorderhaug** [comment]
**To change the height of a `DropzoneArea`:**

1. Set the `drop-zone-class` property of the DropzoneArea component to a custom class name, such as "drop-zone-area".
2. Set the height in your css style sheet.

For example, to fill the drop zone area to the height of a container:

```css
.drop-zone-area {
    height: 100%;
}

**Comment by samithahansaka** [comment]
Thanks a lot.

**Comment by miliu99** [comment]
How comes this doesn't work for me? Should I use drop-zone-class="drop-zone-area" or className="drop-zone-area"? I tried both but no effect at all.

**Comment by njordhov** [comment]
Seems like `drop-zone-area` has been renamed to `dropZone`. Alternatively, provide `drop-zone-area` (or a classname of your liking) in the attribute `dropzoneClass` of the `DropzoneArea` component. See https://github.com/Yuvaleros/material-ui-dropzone/blob/master/src/DropzoneArea.js
