### ISSUE TITLE
Deprecation error from material-ui

### ISSUE THREAD

**Issue by cshanejennings** [Yuvaleros/material-ui-dropzone#53]
When completing a file drag action, I get the following error log in the console.  (I thing it's just a log and not a true error).

Not presenting this as critical, just reporting the error message in case it's helpful. I tried stepping through the debug logs things quickly got convoluted so I'm not sure I can offer much help beyond sharing the message and that SnackbarContentWrapper seems to be the only class using theme.spacing.unit

```
index.js:1375 Warning: Material-UI: theme.spacing.unit usage has been deprecated.
It will be removed in v5.
You can replace `theme.spacing.unit * y` with `theme.spacing(y)`.

You can use the `https://github.com/mui-org/material-ui/tree/master/packages/material-ui-codemod/README.md#theme-spacing-api` migration helper to make the process smoother.
```

**Comment by natevarghese** [comment]
+1

**Comment by MarkusKonk** [comment]
@cshanejennings I have the same warning messsage. Does the Dropzone still take your files or doesn't it work at all?

**Comment by cshanejennings** [comment]
It still takes my files.  I think it's just a deprecation warning, but serious enough where a near future update might cause a breaking change because they did take the time to throw it as a caught exception rather than as just a warning.

**Comment by Yuvaleros** [comment]
@cshanejennings Are you still getting this message on the latest version? tried dragging a file using the example and didn't see this warning.

**Comment by cshanejennings** [comment]
Still getting it in 2.4.0, yes.
Here are my dependencies:

```
    "@material-ui/core": "^4.1.1",
    "@material-ui/icons": "^4.2.0",
    "axios": "^0.19.0",
    "clsx": "^1.0.4",
    "csv": "^5.1.1",
    "enzyme": "^3.10.0",
    "enzyme-adapter-react-16": "^1.14.0",
    "lodash": "^4.17.11",
    "material-ui-dropzone": "^2.4.0",
    "moment": "^2.24.0",
    "node-sass": "^4.12.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-redux": "^7.1.0",
    "react-router": "^5.0.1",
    "react-router-dom": "^5.0.1",
    "react-scripts": "3.0.1",
    "react-test-renderer": "^16.8.6",
    "redux": "^4.0.1",
    "redux-thunk": "^2.3.0"
```

**Comment by IIndecent** [comment]
@material-ui v4.0.0 the spacing syntax has been changed, and will be removed in v5
`theme.spacing.unit`
should simply be changed to
`theme.spacing(x)`
where x is a value to multiply the theme spacing by. They have a more comprehensive explanation [here](https://github.com/mui-org/material-ui/blob/master/packages/material-ui-codemod/README.md#theme-spacing-api%60). More on implementation of spacing in v4 [here](https://material-ui.com/customization/spacing/). According to their [milestones](https://github.com/mui-org/material-ui/milestones) v5 isn't set to release until January 2020.

**Comment by peterchq** [comment]
I created a PR to fix this:
https://github.com/Yuvaleros/material-ui-dropzone/pull/71

**Comment by saumyakaran** [comment]
@Yuvaleros I was looking for a solution to fix the following error and came across this issue... It seems that this was closed a while ago, but even after updating the package using npm, I still seem to be running into the same error...

**Comment by Yuvaleros** [comment]
@saumyakaran,  Please try again, I published the latest version to NPM.

**Comment by saumyakaran** [comment]
@Yuvaleros I updated the package using the following command ```npm install --save material-ui-dropzone``` 
![Screenshot 2019-10-14 at 8 25 23 PM](https://user-images.githubusercontent.com/40575379/66760997-c9e6fa00-eec0-11e9-9ddf-079f6bc55c82.png)

The screenshot above shows my terminal window after running the command... Also, there seems to be a new error as well... I've attached the screenshot of my browser console below...
![Screenshot 2019-10-14 at 8 33 28 PM](https://user-images.githubusercontent.com/40575379/66761603-f18a9200-eec1-11e9-988f-c5d5e45303ac.png)
![Screenshot 2019-10-14 at 8 33 39 PM](https://user-images.githubusercontent.com/40575379/66761604-f2232880-eec1-11e9-8eb5-ce14840440c6.png)

I'm not sure if I'm doing something wrong... If you need more info please let me know what info you might need. Thanks!
