### ISSUE TITLE
Initialize the drop zone with existing file

### ISSUE THREAD

**Issue by mohitkumarCLS** [Yuvaleros/material-ui-dropzone#56]
Is there any way to initialize the drop-zone area with existing files? 
As i want to add images with already uploaded images, so want to initialize the drop-zone area with existing and show to the user in drop-zone area.

**Comment by arielleguizamon** [comment]
👍

**Comment by nguyengiahuynh** [comment]
how can we do it ???

**Comment by nmenal** [comment]
```
<DropzoneArea
        initialFiles={[
          "https://images.pexels.com/photos/1909603/pexels-photo-1909603.jpeg"
        ]}
      />
```
