### ISSUE TITLE
Adding fullscreen property to support withMobileDialog

### ISSUE THREAD

**Issue by nicholasdickey** [Yuvaleros/material-ui-dropzone#58]
Would be great if support for withMobileDialog higher order component could be added.
Thanks!

**Comment by panz3r** [comment]
Should be possible to achieve using the available `dialogProps` prop.

Also `withMobileDialog` has been deprecated by `material-ui` and will be removed in next version (`5.x`), see [here](https://github.com/mui-org/material-ui/pull/14992) and [here](https://github.com/mui-org/material-ui/issues/20012) for more details.

Closing this issue.
