### ISSUE TITLE
use only JSS for styling (no CSS)

### ISSUE THREAD

**Issue by haysclark** [Yuvaleros/material-ui-dropzone#6]
It would be more consistant if _material-ui-dropzone_ only used CSS or JSS, instead of both.  An all JSS solution might be the better route to align with Material-UI v4 goals.

**Comment by jackpilowsky** [comment]
Seems I misunderstood the documentation when I switched back to CSS in order to implement the keyframes

**Comment by haysclark** [comment]
I just noticed that my code is causing some hitching in the animation... I'll see if I can sort is out.

**Comment by haysclark** [comment]
@jackpilowsky I hear you! JSS can be rather unintuitive at times, I wasted a lot of time yesterday trying to sort out issues with ```&:hover```. 😄
