### ISSUE TITLE
Material-ui 4

### ISSUE THREAD

**Issue by TerjeNorderhaug** [Yuvaleros/material-ui-dropzone#60]
I am successfully using version 2.4.0 with material-ui  4 and suggest the dependencies are updated accordingly:

```javascript
"@material-ui/core": "^3.6.1 || ^4.0.0",
"@material-ui/icons": "^3.0.2 || ^4.0.0",
```

**Comment by Yuvaleros** [comment]
Thanks,
Added to 2.4.1

**Comment by HonzaTuron** [comment]
Hey @Yuvaleros, would library works with `@material-ui/icons": "^3.0.2 || ^4.0.0` also in dependencies? 
See
https://github.com/Yuvaleros/material-ui-dropzone/blob/master/package.json#L80
