### ISSUE TITLE
please need change acceptClassName and rejectClassName

### ISSUE THREAD

**Issue by sirsaeta** [Yuvaleros/material-ui-dropzone#73]
I need to customize the colors at the time of dragenter and dragleave to be able to assign a class when that event is executed. Please help-me
acceptClassName: classes.stripes,
rejectClassName: classes.rejectStripes,

**Comment by madebyem** [comment]
did you find an answear? i need it also :)

**Comment by panz3r** [comment]
Related to #125, improving support for MUI Theme should allow changing `accept` and `reject` feedback also.
