### ISSUE TITLE
Possibility to override file uploaded

### ISSUE THREAD

**Issue by sebay00** [Yuvaleros/material-ui-dropzone#75]
Hey first, cool lib guys 👍 thx

I would like to upload only one file, but I would like to be able to override my file loaded by uploading a new file without removing the first file uploaded before.

Is there an existing way to do that ?

**Comment by dmbarry86** [comment]
I would like this too. Does anybody know of a workaround in the meantime?

**Comment by giveli** [comment]
I’m also interested in knowing the answer !

**Comment by max-carroll** [comment]
There doesn't appear to be any challenge against implementing this and seems to be much support for this feature, I suppose someone can go ahead and create a PR for it, I cant promise I'll do it but Ill see how much time I get

**Comment by panz3r** [comment]
Hi,

Thanks for your feedbacks, a way we could try to solve this issue might be to create an "controlled" version of the `DropzoneArea` component (something named `DropzoneAreaBase` which could become the base for the current one) with the state management logic extracted to allow handling files directly from outside (instead of keeping it in sync).

**Comment by max-carroll** [comment]
Could we have a prop to enable some kind of file replacement behaviour 

like maybe `filesOverflow`
'filo' // First In Last Out (where the added files move through like a conveyor belt when the file limit is exceeded
'lifo', // Last in First Out (where the last ones added are replaced as the limit is exceeded
'none' // we don't allow overflow behaviour and we will show the alert that the file limit is reached

**Comment by panz3r** [comment]
Hi @max-carroll ,

I think that maybe it's best to avoid implementing such complex and "use-case"-specific logics inside the module and try to allow the user to choose how to implement it.

I'll try to work on my original suggestion (creating an "controlled" version of both components) as soon as this weekend and see if that can help with this issue.

**Comment by max-carroll** [comment]
Yeah I think you're right, we could prehaps provide an overFlow function which allows them to manipulate the files however they like
