### ISSUE TITLE
Styling internals of the dialog

### ISSUE THREAD

**Issue by mikiasmohamed** [Yuvaleros/material-ui-dropzone#80]
I wanted to add new styles such as padding, text color, background etc. I tried using the `dropzoneClass` attribute to do so. But the UI is not updating. Can you please provide an example on how to add custom styles?

**Comment by Liiva** [comment]
I'm not sure what component you intend with "dialog" but I styled the `DropzoneArea` using this code snippet, hopefully this helps.

```
import makeStyles from "@material-ui/core/styles/makeStyles";

const useStyles = makeStyles(theme => ({
  dropZone: {
    minHeight: "100%",
    marginBottom: "10px",
    paddingBottom: "10px"
  },
  dropzoneParagraph: {
    fontSize: "1rem"
  }
}));

const YourComponent = ({ someProp, ...props }) => {
  const classes = useStyles(props);

  return (
      <DropzoneArea
        classes={classes}
        // ... other dropzone area props
      />
  );
}
```

**Comment by panz3r** [comment]
Related to #125 , improving support for MUI Theme should allow changing internal dialog style also.
