### ISSUE TITLE
Single file mode

### ISSUE THREAD

**Issue by Sangrene** [Yuvaleros/material-ui-dropzone#81]
Would a single file mode fit into this project roadmap ?
By single file mode I mean :
- Can select maximum one file
- If new file is selected, replace the previous one
- Preview in the drop zone area

If this feature fits in this library, I would gladly work on a PR.

**Comment by WJ89** [comment]
It looks like most of this is being addressed in https://github.com/Yuvaleros/material-ui-dropzone/pull/98 by @dimitriadamou

**Comment by Sangrene** [comment]
I totally forget that and ended up writing my own file dropzone with more fine grained customization... oops ʕ•ᴥ•ʔ
