### ISSUE TITLE
How do you handle image upload orientation 

### ISSUE THREAD

**Issue by cgibsonmm** [Yuvaleros/material-ui-dropzone#82]
After the drag and drop it is showing image previews that are rotated is there a way to handle the preview image orientation?

**Comment by Yuvaleros** [comment]
Currently there is no option to rotate the preview images.

**Comment by cgibsonmm** [comment]
feature-request?

**Comment by panz3r** [comment]
Since the "Preview" section is getting a lot of attention in the last period, we're going to improve it a bit.
You can follow the development and contribute with your ideas/feedbacks on this issue #166 .

Closing this issue in favour of the new "umbrella" one.
