### ISSUE TITLE
Dropzone does not work at Windows

### ISSUE THREAD

**Issue by Kuharenko** [Yuvaleros/material-ui-dropzone#88]
I am trying to upload csv file like this:
`<DropzoneArea
                        className="my_drop" style={{margin: 0}}
                        dropzoneClass={'DropzoneArea'}
                        showPreviews={false}
                        accept=".csv"
                        showAlerts={true}
                        acceptedFiles={[
                            'application/vnd.ms-excel',
                            'text/csv',
                            'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                            'xls',
                            'text/x-csv',
                            'application/csv',
                            'application/x-csv',
                            'text/comma-separated-values',
                            'text/x-comma-separated-values',
                            'text/tab-separated-values',
                        ]}
                        filesLimit={1}
                        dropzoneText={'Drop file here, or click to select file'}
                        cancelButtonText={false}
                        showPreviewsInDropzone={true}
                        onChange={this.props.onDrop}
                        onDelete={this.props.onCancel}
                        onDropRejected={this.handleReject}
                    />`

and got different results at different OS. At Debian and iOS it works fine, but on Windows 10 I got reject message "This mime type does not support". Log at Windows says 
`type: ""`
but on Linux, iOS it:
`type: "text/csv"`

**Comment by kaleychikeugene** [comment]
> I am trying to upload csv file like this:
> `<DropzoneArea className="my_drop" style={{margin: 0}} dropzoneClass={'DropzoneArea'} showPreviews={false} accept=".csv" showAlerts={true} acceptedFiles={[ 'application/vnd.ms-excel', 'text/csv', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'xls', 'text/x-csv', 'application/csv', 'application/x-csv', 'text/comma-separated-values', 'text/x-comma-separated-values', 'text/tab-separated-values', ]} filesLimit={1} dropzoneText={'Drop file here, or click to select file'} cancelButtonText={false} showPreviewsInDropzone={true} onChange={this.props.onDrop} onDelete={this.props.onCancel} onDropRejected={this.handleReject} />`
> 
> and got different results at different OS. At Debian and iOS it works fine, but on Windows 10 I got reject message "This mime type does not support". Log at Windows says
> `type: ""`
> but on Linux, iOS it:
> `type: "text/csv"`

Try use `acceptedFiles={[...,'.csv']}`.
