### ISSUE TITLE
Unable to preview png file

### ISSUE THREAD

**Issue by shailesh-padave** [Yuvaleros/material-ui-dropzone#90]
JPEG file preview works fine but png file preview not working, it shows `Anchor` button. Is there any workaround for this issue? OR has anyone faced this issue in past?

<img width="1220" alt="image" src="https://user-images.githubusercontent.com/49918163/70188532-cd6b5600-16a5-11ea-812e-e314a8c1aa3e.png">

**Comment by faupol3** [comment]
@shailesh-padave in my case some files had a double extension which prevented identifying the file as an image and returned the AttachedFileIcon element instead.
Added the following PR to fix image identification, should probably fix your issue too. Hard to tell with no details.
https://github.com/Yuvaleros/material-ui-dropzone/pull/101
