### ISSUE TITLE
set name for <input> element

### ISSUE THREAD

**Issue by mnlbox** [Yuvaleros/material-ui-dropzone#92]
Hi guys,
I want set name attribute for `<input>` generated by `<DropzoneArea />` because I'm using `multer` like this:
```
router.post('api/image', upload.single('image'), async (req, res, next) => {
```
And I want set `name = "image" `. Can you help me about this?

**/CC:** @Yuvaleros, @yuvfolinks

**Comment by mnlbox** [comment]
Guys, it seems that DropZone component support `inputProps` property for this:
https://github.com/Yuvaleros/material-ui-dropzone/blob/063a84132db08624cd6181d7cc8cfb19da24203e/dist/index.js#L1027

**Comment by mnlbox** [comment]
It seems it also supports `name` attribute.
https://github.com/Yuvaleros/material-ui-dropzone/blob/063a84132db08624cd6181d7cc8cfb19da24203e/dist/index.js#L1037

Any plan to support the complete DropZone attribute?

**Comment by versedi** [comment]
Either I'm doing something wrong or `inputProps` and `name` don't work on `DropzoneArea`.

**Comment by versedi** [comment]
Why this isn't supported I have no idea.

Unfortunately I can't use `material-ui-dropzone` because it's lacking a must have issue.

We're using json schema to validate our forms and that can't be done without assigning `name` attribute to the input field.
