### ISSUE TITLE
remove console logs from Dropzone dialog 

### ISSUE THREAD

**Issue by Morteza-Jenabzadeh** [Yuvaleros/material-ui-dropzone#96]
Hi 
thanks for your handy project. I have just a problem which is really getting on my nerves.
I don't know why console logs in dropzoe dialog wasn't remove after development.
can i get a fork and remove them? or make an option to disable them?
Best Regards

**Comment by chattling** [comment]
I created pull request for this - #102

**Comment by Yuvaleros** [comment]
Thanks. Merged pull request - closing.
